[vlan] Vlan deletion is not allowed when there are members assigned to it (#6361)
allas-nvidia/sonic-utilities pull request #2
Opened 2021-02-01 13:43 UTC by allas-nvidia

Signed-off-by: allas <allas@nvidia.com>

**- What I did**
In vlan.py , function del_vlan added validation if there is no members assigned to this VLAN. If there are members - the execution of this command is failed with error on the screen.
**- How I did it**
Added validation of the VLAN_MEMBER_CFG_TABLE with the key VLAN_ID. If there are entries with this VLAN_ID - print error:
 VLAN ID {} can not be removed. First remove all members assigned to this VLAN.
User should remove all members assigned to this VLAN, and after that he can delete vlan.
**- How to verify it**
1.
> sudo config vlan add 200
> sudo config vlan member add 200 Ethernet0
> sudo config vlan del 200
In this case - you will see error as there are members assigned to this VLAN
2.
> sudo config vlan member del 200 Ethernet0
> sudo config vlan del 200
Will pass.

**- Previous command output (if the output of a command-line utility has changed)**

**- New command output (if the output of a command-line utility has changed)**

2021-02-02 01:41 UTC, Junchao-Mellanox requested changes

2021-02-02 01:41 UTC, Junchao-Mellanox commented on config/vlan.py
> +    if keys != []:
To check if a list is empty, we usually use:
```python
if keys:
```

2021-02-02 01:41 UTC, Junchao-Mellanox commented on tests/vlan_test.py
> +        result = runner.invoke(config.config.commands["vlan"].commands["del"], ["1000"], obj=db)
Suggest to get all VLAN members in the VLAN and remove them using a for loop.

2021-02-02 07:53 UTC, liat-grozovik commented
@allas-nvidia  can you please add the expected error in the commit message under the previous and new command output section?

2021-02-03 01:19 UTC, Junchao-Mellanox requested changes

2021-02-03 01:19 UTC, Junchao-Mellanox commented on tests/vlan_test.py
> +        keys = [ (k, v) for k, v in vlan_member if k == 'Vlan{}'.format(1000) ]
Maybe we can use following?
```python
keys = db.cfgdb.get_table('VLAN_MEMBER')['Vlan1000']
```

2021-02-03 07:22 UTC, Junchao-Mellanox approved these changes

2021-02-03 07:22 UTC, Junchao-Mellanox approved these changes

2021-02-21 08:32 UTC, closed without merging